[user]
	name = Michael Oberst
[alias]
	st = status
	ci = commit
	co = checkout
	br = branch
[core]
	editor = nvim
	fileMode = false
	pager = diff-so-fancy | less --tabs=4 -RFX
[push]
	default = simple
[credential]
	helper = cache
[pull]
	rebase = false
[interactive]
	diffFilter = diff-so-fancy --patch
[init]
	defaultBranch = main
