[user]
	name = Michael Oberst
        email = michael.k.oberst@gmail.com
[alias]
	st = status
	ci = commit
	co = checkout
	br = branch
[core]
	editor = nvim
	fileMode = false
[push]
	default = simple
[credential]
	helper = cache
[pull]
	rebase = false
[init]
	defaultBranch = main
