#!/bin/bash

# NeoVim
alias vim="nvim"

# Crop all pdfs in this folder
alias crop_pdfs="find . -name '*.pdf' -print0 | xargs -0 -I _ pdfcrop _ _"

# Aliases for directory navigation
alias ..="cd .."

# Alias to pretty-print the current path, dirs
alias path='echo -e ${PATH//:/\\n}'
alias dirs='dirs -v'

# Directory stack navigation
alias pd="pushd"
alias pc="pushd +1"
alias pp="popd"

alias tmux="tmux -2"

# Common typos
alias sl="ls"

# Create tex directory 
alias newtex="bash $HOME/repos/setup-env/tex/create_base.sh"

# Wrap common file commands in func that sends to bg and ignores output
function evince {
    nohup evince "$@" > /dev/null 2>&1 & disown
}
